#!/bin/sh
#
#  cpuinfo Makefile (C) 2005-2007 Gwenole Beauchesne
#
-include config.mak

CFLAGS += -Wall

ifeq ($(SRC_PATH),)
SRC_PATH = .
endif

PACKAGE = cpuinfo
ifeq ($(VERSION),)
VERSION := $(shell sed < $(SRC_PATH)/$(PACKAGE).spec -n '/^\%define version[	]*/s///p')
endif
ifeq ($(RELEASE),)
RELEASE := $(shell sed < $(SRC_PATH)/$(PACKAGE).spec -n '/^\%define release[	]*/s///p')
endif
ifeq ($(SVNDATE),)
SVNDATE := $(shell sed < $(SRC_PATH)/$(PACKAGE).spec -n '/^\%define svndate[ 	]*/s///p')
endif
ifeq ($(SVNDATE),)
SVNDATE := $(shell date '+%Y%m%d')
endif
ifeq ($(SNAPSHOT),)
SNAPSHOT := $(shell echo "$(RELEASE)" | grep "^0")
ifeq ($(SNAPSHOT),$(RELEASE))
SNAPSHOT := 1
endif
endif
ifeq ($(SNAPSHOT),1)
VERSION_SUFFIX = -$(SVNDATE)
endif

ifneq ($(DONT_STRIP), yes)
STRIP_OPT = -s
endif

ifeq ($(LN),)
LN = ln
endif
ifeq ($(RANLIB),)
RANLIB = ranlib
endif

CPPFLAGS	= -I. -I$(SRC_PATH)
PICFLAGS	= -fPIC

libcpuinfo_a		= libcpuinfo.a
libcpuinfo_a_SOURCES	= cpuinfo-common.c cpuinfo-x86.c cpuinfo-ppc.c cpuinfo-dmi.c
libcpuinfo_a_OBJECTS	= $(libcpuinfo_a_SOURCES:%.c=%.o)

libcpuinfo_so_major	= 0
libcpuinfo_so_minor	= 0
libcpuinfo_so		= libcpuinfo.so
libcpuinfo_so_SONAME	= $(libcpuinfo_so).$(libcpuinfo_so_major)
libcpuinfo_so_LTLIBRARY	= $(libcpuinfo_so).$(libcpuinfo_so_major).$(libcpuinfo_so_minor).0
libcpuinfo_so_OBJECTS	= $(libcpuinfo_a_SOURCES:%.c=%.os)

cpuinfo_PROGRAM	= cpuinfo
cpuinfo_SOURCES	= cpuinfo.c
cpuinfo_OBJECTS	= $(cpuinfo_SOURCES:%.c=%.o)
ifeq ($(build_static),yes)
cpuinfo_DEPS	= $(libcpuinfo_a)
cpuinfo_LDFLAGS	= $(libcpuinfo_a)
else
cpuinfo_OBJECTS += $(libcpuinfo_a_OBJECTS)
endif

TARGETS		= $(cpuinfo_PROGRAM)
ifeq ($(build_static),yes)
TARGETS		+= $(libcpuinfo_a)
endif
ifeq ($(build_shared),yes)
TARGETS		+= $(libcpuinfo_so)
endif

archivedir	= files/
SRCARCHIVE	= $(PACKAGE)-$(VERSION)$(VERSION_SUFFIX).tar
FILES		= configure Makefile $(PACKAGE).spec
FILES		+= $(wildcard src/*.c)
FILES		+= $(wildcard src/*.h)

all: $(TARGETS)

clean:
	rm -f $(TARGETS) *.o *.os
	rm -f $(libcpuinfo_a) $(libcpuinfo_a_OBJECTS)
	rm -f $(libcpuinfo_so) $(libcpuinfo_so_LTLIBRARY) $(libcpuinfo_so_OBJECTS)

$(cpuinfo_PROGRAM): $(cpuinfo_OBJECTS) $(cpuinfo_DEPS)
	$(CC) -o $@ $(cpuinfo_OBJECTS) $(cpuinfo_LDFLAGS) $(LDFLAGS)

install: install.dirs install.bins
install.dirs:
	mkdir -p $(DESTDIR)$(bindir)

install.bins: $(cpuinfo_PROGRAM)
	install -m 755 $(STRIP_OPT) $(cpuinfo_PROGRAM) $(DESTDIR)$(bindir)/

$(archivedir)::
	[ -d $(archivedir) ] || mkdir $(archivedir) > /dev/null 2>&1

tarball:
	$(MAKE) -C $(SRC_PATH) do_tarball
do_tarball: $(archivedir) $(archivedir)$(SRCARCHIVE).bz2

$(archivedir)$(SRCARCHIVE): $(archivedir) $(FILES)
	BUILDDIR=`mktemp -d /tmp/buildXXXXXXXX`						; \
	mkdir -p $$BUILDDIR/$(PACKAGE)-$(VERSION)					; \
	(cd $(SRC_PATH) && tar c $(FILES)) | tar x -C $$BUILDDIR/$(PACKAGE)-$(VERSION)	; \
	[ "$(SNAPSHOT)" = "1" ] && svndate_def="%" || svndate_def="#"			; \
	sed -e "s/^[%#]define svndate.*/$${svndate_def}define svndate $(SVNDATE)/" 	  \
	  < $(SRC_PATH)/$(PACKAGE).spec							  \
	  > $$BUILDDIR/$(PACKAGE)-$(VERSION)/$(PACKAGE).spec				; \
	(cd $$BUILDDIR && tar cvf $(SRCARCHIVE) $(PACKAGE)-$(VERSION))			; \
	mv -f $$BUILDDIR/$(SRCARCHIVE) $(archivedir)					; \
	rm -rf $$BUILDDIR
$(archivedir)$(SRCARCHIVE).bz2: $(archivedir)$(SRCARCHIVE)
	bzip2 -9vf $(archivedir)$(SRCARCHIVE)

RPMBUILD = \
	RPMDIR=`mktemp -d`								; \
	mkdir -p $$RPMDIR/{SPECS,SOURCES,BUILD,RPMS,SRPMS}				; \
	rpmbuild --define "_topdir $$RPMDIR" -ta $(2) $(1) &&				  \
	find $$RPMDIR/ -name *.rpm -exec mv -f {} $(archivedir) \;			; \
	rm -rf $$RPMDIR

localrpm: $(archivedir)$(SRCARCHIVE).bz2
	$(call RPMBUILD,$<)

changelog: ../common/authors.xml
	svn_prefix=`svn info .|sed -n '/^URL *: .*\/svn\/\(.*\)$$/s//\1\//p'`; \
	svn2cl --strip-prefix=$$svn_prefix --authors=../common/authors.xml || :
	svn commit -m "Generated by svn2cl." ChangeLog

%.o: $(SRC_PATH)/src/%.c
	$(CC) -c $< -o $@ $(CPPFLAGS) $(CFLAGS)

%.os: $(SRC_PATH)/src/%.c
	$(CC) -c $< -o $@  $(CPPFLAGS) $(CFLAGS) $(PICFLAGS)

$(libcpuinfo_a): $(libcpuinfo_a_OBJECTS)
	$(AR) rc $@ $(libcpuinfo_a_OBJECTS)
	$(RANLIB) $@

$(libcpuinfo_so): $(libcpuinfo_so_LTLIBRARY)
	$(LN) -sf $< $@

$(libcpuinfo_so_LTLIBRARY): $(libcpuinfo_so_OBJECTS)
	$(CC) -o $@ -shared -Wl,-soname,$(libcpuinfo_so_SONAME) $(libcpuinfo_so_OBJECTS)
